apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cloudzcp.io/realm: tworld
    cloudzcp.io/project: tworld-biz
    cloudzcp.io/zcpapplication: testnginx
  name: testnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      cloudzcp.io/realm: tworld
      cloudzcp.io/project: tworld-biz
      cloudzcp.io/zcpapplication: testnginx
  template:
    metadata:
      labels:
        cloudzcp.io/realm: tworld
        cloudzcp.io/project: tworld-biz
        cloudzcp.io/zcpapplication: testnginx
      name: testnginx
    spec:
      containers:
      - image: "tworld-registry.skt.cloudzcp.com/kb-test/nginx:latest-6"
        imagePullPolicy: Always
        name: testnginx
      imagePullSecrets:
      - name: kb-harbor-robot
