apiVersion: v1
kind: Service
metadata:
  labels:
    cloudzcp.io/realm: tworld
    cloudzcp.io/project: tworld-biz
    cloudzcp.io/zcpapplication: testnginx
  name: testnginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    cloudzcp.io/realm: tworld
    cloudzcp.io/project: tworld-biz
    cloudzcp.io/zcpapplication: testnginx
  type: ClusterIP
